print("OH you've got cancer! you will die in 2 days :(")
print("I'm just kidding..")
print("we are going to put you in experimental drugs")
print("I found the best way to detect cancer! Please use it.")
print("Test")
print("Hey, it's better to preprocess the image")
